# Project information
site_name: REPO_NAME_OR_SITE_NAME
# defeine TOC or order of website-
nav:
  - Home: index.md
  - Feedback: feedback.md

site_author: Sunny Bhaveen Chandra
site_description: >-
  DESCRIPTION

# Repository
repo_name: c17hawke/REPO_NAME
repo_url: https://github.com/c17hawke/REPO_NAME

# Configuration
theme:
  name: material
  features:
    - navigation.tabs
  language: en
  palette:
    scheme: slate
    primary: green
    accent: lime
#  logo: assets/mainLogo.jpg
  
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/c17hawke
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/c17hawke
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/c17hawke
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/c17hawke/

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML
markdown_extensions:
  - codehilite:
      linenums: true
  - admonition
  - pymdownx.arithmatex
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - pymdownx.highlight
  
  
plugins:
  - search

copyright: |
  &copy; 2021 <a href="https://github.com/c17hawke"  target="_blank" rel="noopener">Sunny Bhaveen Chandra</a>
